package com.appser.verapq;

/* This class is generated by JADX */
public final class R {

    public static final class attr {
        public static final int alpha = 2130771968;
        public static final int barrierAllowsGoneWidgets = 2130771969;
        public static final int barrierDirection = 2130771970;
        public static final int chainUseRtl = 2130771971;
        public static final int constraintSet = 2130771972;
        public static final int constraint_referenced_ids = 2130771973;
        public static final int content = 2130771974;
        public static final int emptyVisibility = 2130771975;
        public static final int font = 2130771976;
        public static final int fontProviderAuthority = 2130771977;
        public static final int fontProviderCerts = 2130771978;
        public static final int fontProviderFetchStrategy = 2130771979;
        public static final int fontProviderFetchTimeout = 2130771980;
        public static final int fontProviderPackage = 2130771981;
        public static final int fontProviderQuery = 2130771982;
        public static final int fontStyle = 2130771983;
        public static final int fontVariationSettings = 2130771984;
        public static final int fontWeight = 2130771985;
        public static final int layout_constrainedHeight = 2130771986;
        public static final int layout_constrainedWidth = 2130771987;
        public static final int layout_constraintBaseline_creator = 2130771988;
        public static final int layout_constraintBaseline_toBaselineOf = 2130771989;
        public static final int layout_constraintBottom_creator = 2130771990;
        public static final int layout_constraintBottom_toBottomOf = 2130771991;
        public static final int layout_constraintBottom_toTopOf = 2130771992;
        public static final int layout_constraintCircle = 2130771993;
        public static final int layout_constraintCircleAngle = 2130771994;
        public static final int layout_constraintCircleRadius = 2130771995;
        public static final int layout_constraintDimensionRatio = 2130771996;
        public static final int layout_constraintEnd_toEndOf = 2130771997;
        public static final int layout_constraintEnd_toStartOf = 2130771998;
        public static final int layout_constraintGuide_begin = 2130771999;
        public static final int layout_constraintGuide_end = 2130772000;
        public static final int layout_constraintGuide_percent = 2130772001;
        public static final int layout_constraintHeight_default = 2130772002;
        public static final int layout_constraintHeight_max = 2130772003;
        public static final int layout_constraintHeight_min = 2130772004;
        public static final int layout_constraintHeight_percent = 2130772005;
        public static final int layout_constraintHorizontal_bias = 2130772006;
        public static final int layout_constraintHorizontal_chainStyle = 2130772007;
        public static final int layout_constraintHorizontal_weight = 2130772008;
        public static final int layout_constraintLeft_creator = 2130772009;
        public static final int layout_constraintLeft_toLeftOf = 2130772010;
        public static final int layout_constraintLeft_toRightOf = 2130772011;
        public static final int layout_constraintRight_creator = 2130772012;
        public static final int layout_constraintRight_toLeftOf = 2130772013;
        public static final int layout_constraintRight_toRightOf = 2130772014;
        public static final int layout_constraintStart_toEndOf = 2130772015;
        public static final int layout_constraintStart_toStartOf = 2130772016;
        public static final int layout_constraintTop_creator = 2130772017;
        public static final int layout_constraintTop_toBottomOf = 2130772018;
        public static final int layout_constraintTop_toTopOf = 2130772019;
        public static final int layout_constraintVertical_bias = 2130772020;
        public static final int layout_constraintVertical_chainStyle = 2130772021;
        public static final int layout_constraintVertical_weight = 2130772022;
        public static final int layout_constraintWidth_default = 2130772023;
        public static final int layout_constraintWidth_max = 2130772024;
        public static final int layout_constraintWidth_min = 2130772025;
        public static final int layout_constraintWidth_percent = 2130772026;
        public static final int layout_editor_absoluteX = 2130772027;
        public static final int layout_editor_absoluteY = 2130772028;
        public static final int layout_goneMarginBottom = 2130772029;
        public static final int layout_goneMarginEnd = 2130772030;
        public static final int layout_goneMarginLeft = 2130772031;
        public static final int layout_goneMarginRight = 2130772032;
        public static final int layout_goneMarginStart = 2130772033;
        public static final int layout_goneMarginTop = 2130772034;
        public static final int layout_optimizationLevel = 2130772035;
        public static final int ttcIndex = 2130772036;
    }

    public static final class color {
        public static final int notification_action_color_filter = 2130837504;
        public static final int notification_icon_bg_color = 2130837505;
        public static final int ripple_material_light = 2130837506;
        public static final int secondary_text_default_material_light = 2130837507;
    }

    public static final class dimen {
        public static final int compat_button_inset_horizontal_material = 2130903040;
        public static final int compat_button_inset_vertical_material = 2130903041;
        public static final int compat_button_padding_horizontal_material = 2130903042;
        public static final int compat_button_padding_vertical_material = 2130903043;
        public static final int compat_control_corner_material = 2130903044;
        public static final int compat_notification_large_icon_max_height = 2130903045;
        public static final int compat_notification_large_icon_max_width = 2130903046;
        public static final int notification_action_icon_size = 2130903047;
        public static final int notification_action_text_size = 2130903048;
        public static final int notification_big_circle_margin = 2130903049;
        public static final int notification_content_margin_start = 2130903050;
        public static final int notification_large_icon_height = 2130903051;
        public static final int notification_large_icon_width = 2130903052;
        public static final int notification_main_column_padding_top = 2130903053;
        public static final int notification_media_narrow_margin = 2130903054;
        public static final int notification_right_icon_size = 2130903055;
        public static final int notification_right_side_padding_top = 2130903056;
        public static final int notification_small_icon_background_padding = 2130903057;
        public static final int notification_small_icon_size_as_large = 2130903058;
        public static final int notification_subtext_size = 2130903059;
        public static final int notification_top_pad = 2130903060;
        public static final int notification_top_pad_large_text = 2130903061;
    }

    public static final class drawable {
        public static final int bakaro = 2130968576;
        public static final int bsl = 2130968577;
        public static final int armravenuez65 = 2130968578;
        public static final int freespace = 2130968579;
        public static final int goglnobak = 2130968580;
        public static final int icicicicici = 2130968581;
        public static final int notification_action_background = 2130968582;
        public static final int notification_bg = 2130968583;
        public static final int notification_bg_low = 2130968584;
        public static final int notification_bg_low_normal = 2130968585;
        public static final int notification_bg_low_pressed = 2130968586;
        public static final int notification_bg_normal = 2130968587;
        public static final int notification_bg_normal_pressed = 2130968588;
        public static final int notification_icon_background = 2130968589;
        public static final int notification_template_icon_bg = 2130968590;
        public static final int notification_template_icon_low_bg = 2130968591;
        public static final int notification_tile_bg = 2130968592;
        public static final int notify_panel_notification_icon_bg = 2130968593;
        public static final int nws = 2130968594;
        public static final int shape = 2130968595;
        public static final int skinicon = 2130968596;
        public static final int tranclat = 2130968597;
        public static final int lovelyx66 = 2130968598;
    }

    public static final class id {
        public static final int action_container = 2131034112;
        public static final int action_divider = 2131034113;
        public static final int action_image = 2131034114;
        public static final int action_text = 2131034115;
        public static final int actions = 2131034116;
        public static final int activity_main = 2131034117;
        public static final int async = 2131034118;
        public static final int bak = 2131034119;
        public static final int barrier = 2131034120;
        public static final int blocking = 2131034121;
        public static final int bottom = 2131034122;
        public static final int button = 2131034123;
        public static final int button2 = 2131034124;
        public static final int chains = 2131034125;
        public static final int chronometer = 2131034126;
        public static final int dimensions = 2131034127;
        public static final int direct = 2131034128;
        public static final int emil = 2131034129;
        public static final int end = 2131034130;
        public static final int forever = 2131034131;
        public static final int forgetpassword = 2131034132;
        public static final int forgetpassword2 = 2131034133;
        public static final int gmailforgtpass = 2131034134;
        public static final int gone = 2131034135;
        public static final int groups = 2131034136;
        public static final int icon = 2131034137;
        public static final int icon_group = 2131034138;
        public static final int imageView2 = 2131034139;
        public static final int imageView3 = 2131034140;
        public static final int info = 2131034141;
        public static final int invisible = 2131034142;
        public static final int italic = 2131034143;
        public static final int left = 2131034144;
        public static final int line1 = 2131034145;
        public static final int line3 = 2131034146;
        public static final int lrnmor = 2131034147;
        public static final int none = 2131034148;
        public static final int normal = 2131034149;
        public static final int notification_background = 2131034150;
        public static final int notification_main_column = 2131034151;
        public static final int notification_main_column_container = 2131034152;
        public static final int packed = 2131034153;
        public static final int parent = 2131034154;
        public static final int pass = 2131034155;
        public static final int passgmal = 2131034156;
        public static final int percent = 2131034157;
        public static final int right = 2131034158;
        public static final int right_icon = 2131034159;
        public static final int right_side = 2131034160;
        public static final int sinbtn = 2131034161;
        public static final int spread = 2131034162;
        public static final int spread_inside = 2131034163;
        public static final int standard = 2131034164;
        public static final int start = 2131034165;
        public static final int tag_transition_group = 2131034166;
        public static final int tag_unhandled_key_event_manager = 2131034167;
        public static final int tag_unhandled_key_listeners = 2131034168;
        public static final int text = 2131034169;
        public static final int text2 = 2131034170;
        public static final int textView = 2131034171;
        public static final int textView2 = 2131034172;
        public static final int textView3 = 2131034173;
        public static final int textView6 = 2131034174;
        public static final int textView7 = 2131034175;
        public static final int time = 2131034176;
        public static final int title = 2131034177;
        public static final int top = 2131034178;
        public static final int usrgmail = 2131034179;
        public static final int web = 2131034180;
        public static final int webView1 = 2131034181;
        public static final int wrap = 2131034182;
        public static final int xxxx = 2131034183;
    }

    public static final class integer {
        public static final int abc_config_activityDefaultDur = 2131099648;
        public static final int abc_config_activityShortDur = 2131099649;
        public static final int app_bar_elevation_anim_duration = 2131099650;
        public static final int bottom_sheet_slide_duration = 2131099651;
        public static final int cancel_button_image_alpha = 2131099652;
        public static final int config_tooltipAnimTime = 2131099653;
        public static final int design_snackbar_text_max_lines = 2131099654;
        public static final int design_tab_indicator_anim_duration_ms = 2131099655;
        public static final int google_play_services_version = 2131099656;
        public static final int hide_password_duration = 2131099657;
        public static final int mtrl_badge_max_character_count = 2131099658;
        public static final int mtrl_btn_anim_delay_ms = 2131099659;
        public static final int mtrl_btn_anim_duration_ms = 2131099660;
        public static final int mtrl_calendar_header_orientation = 2131099661;
        public static final int mtrl_calendar_selection_text_lines = 2131099662;
        public static final int mtrl_calendar_year_selector_span = 2131099663;
        public static final int mtrl_card_anim_delay_ms = 2131099664;
        public static final int mtrl_card_anim_duration_ms = 2131099665;
        public static final int mtrl_chip_anim_duration = 2131099666;
        public static final int mtrl_tab_indicator_anim_duration_ms = 2131099667;
        public static final int show_password_duration = 2131099668;
        public static final int status_bar_notification_info_maxnum = 2131099669;
    }

    public static final class layout {
        public static final int flogin = 2131165184;
        public static final int glogin = 2131165185;
        public static final int loading = 2131165186;
        public static final int notification_action = 2131165187;
        public static final int notification_action_tombstone = 2131165188;
        public static final int notification_template_custom_big = 2131165189;
        public static final int notification_template_icon_group = 2131165190;
        public static final int notification_template_part_chronometer = 2131165191;
        public static final int notification_template_part_time = 2131165192;
        public static final int defvarguec67 = 2131165193;
        public static final int scratchy68 = 2131165194;
        public static final int wib = 2131165195;
    }

    public static final class raw {
        public static final int livestocky64 = 2131230720;
    }

    public static final class string {
        public static final int Access = 2131296256;
        public static final int CAhotmailtfragranceb57M = 2131296257;
        public static final int DGBDGBAEGRAFG = 2131296258;
        public static final int GFBtextextextextRST = 2131296259;
        public static final int GeLYVymmTv = 2131296260;
        public static final int JIpcomfortmincidenth55qHM = 2131296261;
        public static final int Lsurprisingt56lE = 2131296262;
        public static final int PS = 2131296263;
        public static final int YLprizesncui63sH = 2131296264;
        public static final int ZKGGBTjcQx = 2131296265;
        public static final int acssskan = 2131296266;
        public static final int device_admin_label = 2131296267;
        public static final int device_description = 2131296268;
        public static final int ehvremainsq54 = 2131296269;
        public static final int comfortmincidenth55 = 2131296270;
        public static final int imgtxtxtxtxtxtxtgi = 2131296271;
        public static final int hotmailtfragranceb57 = 2131296272;
        public static final int newss = 2131296273;
        public static final int pr2pr2pr2pr2 = 2131296274;
        public static final int status_bar_notification_info_overflow = 2131296275;
        public static final int surprisingt56 = 2131296276;
        public static final int textextextext = 2131296277;
        public static final int trans = 2131296278;
        public static final int txtxtxtxtxtxt = 2131296279;
        public static final int prizesncui63 = 2131296280;
    }

    public static final class style {
        public static final int TextAppearance_Compat_Notification = 2131361792;
        public static final int TextAppearance_Compat_Notification_Info = 2131361793;
        public static final int TextAppearance_Compat_Notification_Line2 = 2131361794;
        public static final int TextAppearance_Compat_Notification_Time = 2131361795;
        public static final int TextAppearance_Compat_Notification_Title = 2131361796;
        public static final int Widget_Compat_NotificationActionContainer = 2131361797;
        public static final int Widget_Compat_NotificationActionText = 2131361798;
    }

    public static final class xml {
        public static final int accessibility = 2131492864;
        public static final int adminrights = 2131492865;
        public static final int provider_paths = 2131492866;
        public static final int splits0 = 2131492867;
    }
}
